version: "2"

services:
  bot:
    build: .
    volumes:
      - .:/code
      - data:/data
    environment:
      TMPDIR: /code/tmp
      DEBUG: '1'
      TWITTER_CONSUMER_KEY:
      TWITTER_CONSUMER_SECRET:
      TWITTER_ACCESS_TOKEN:
      TWITTER_ACCESS_TOKEN_SECRET:
      SILENT_MODE:

volumes:
  data: {}
